name: Train Diabetes Model

on:
  push:
    branches:
      - main

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Azure CLI and ML extension
        run: |
          pip install azure-cli
          az extension add -n ml

      - name: Run experiment job in dev
        run: |
          az ml job create --file ./experiment-job.yml \
            --workspace-name workspace_adnane_dev \
            --resource-group adnane_student_ressource \
            --stream

  production:
    runs-on: ubuntu-latest
    needs: experiment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Azure CLI and ML extension
        run: |
          pip install azure-cli
          az extension add -n ml

      - name: Run production job
        run: |
          az ml job create --file ./production-job.yml \
            --workspace-name workspace_adnane_production \
            --resource-group adnane_student_ressource \
            --stream
